[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ictVoIP Billing"
authors = [{name = "Jim", email = "jevans@ictvoip.ca"}]
dynamic = ["version", "description"]
